POST http://atlas-sql-65bac0cc9137e30ecb9386ba-8xakz.a.query.mongodb.net/api/products
Content-Type: application/json

{
  "nombre": "Pelota de fútbol",
  "precio": 20,
  "descripcion": "Pelota de fútbol oficial para practicar el deporte favorito de millones de personas en todo el mundo."
}